# Project Name
TARGET = liminal_reverb

# Sources
CPP_SOURCES = liminal_reverb.cpp \
              filters/ap_filter.cpp \
              filters/lp_filter.cpp \
              filters/hp_filter.cpp \
              effects/fdn_reverb.cpp \
              utils/hw_utils.cpp \
              utils/sw_utils.cpp \
              liminal_reverb/reverb_effect.cpp

# Library Locations
LIBDAISY_DIR = ../libDaisy/
DAISYSP_DIR = ../DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile